"use strict";
define(['model'],function($model){
	return new $model(
			{
				meta:{
					title: 'General Components',
				},
				data:{"components":[{"recordbooks":{"id":"1","faculty_load_id":"2"},"recordbook_details":{"period_id":"1","template_id":"1"},"templates":{"name":"Template Sample 1"},"template_details":{"general_component_id":"PT","index_order":"2.0","percentage":"30.00"},"general_components":{"id":"PT","name":"Performance Task"},"measurable_item_count":4},{"recordbooks":{"id":"1","faculty_load_id":"2"},"recordbook_details":{"period_id":"1","template_id":"1"},"templates":{"name":"Template Sample 1"},"template_details":{"general_component_id":"QA","index_order":"3.0","percentage":"40.00"},"general_components":{"id":"QA","name":"Quarterly Assessment"},"measurable_item_count":4},{"recordbooks":{"id":"1","faculty_load_id":"2"},"recordbook_details":{"period_id":"1","template_id":"1"},"templates":{"name":"Template Sample 1"},"template_details":{"general_component_id":"WW","index_order":"1.0","percentage":"30.00"},"general_components":{"id":"WW","name":"Written Works"},"measurable_item_count":5}],"measurables":[{"MeasurableItem":{"id":"1","general_component_id":"PT","header":"P1","perfect_score":"100","percentage":"100.00","base":"0","is_item":"1"}},{"MeasurableItem":{"header":"Total","is_item":false,"is_abbrev":false}},{"MeasurableItem":{"header":"P.S","tooltip":"Perfect Score","is_item":false,"is_abbrev":true}},{"MeasurableItem":{"header":"W.S","tooltip":"Weighted Score","is_item":false,"is_abbrev":true}},{"MeasurableItem":{"general_component_id":"QA","header":"Default","perfect_score":"0","percentage":"0","base":"0","is_item":true}},{"MeasurableItem":{"header":"Total","is_item":false,"is_abbrev":false}},{"MeasurableItem":{"header":"P.S","tooltip":"Perfect Score","is_item":false,"is_abbrev":true}},{"MeasurableItem":{"header":"W.S","tooltip":"Weighted Score","is_item":false,"is_abbrev":true}},{"MeasurableItem":{"id":"2","general_component_id":"WW","header":"Q1","perfect_score":"100","percentage":"100.00","base":"0","is_item":"1"}},{"MeasurableItem":{"id":"3","general_component_id":"WW","header":"Q2","perfect_score":"100","percentage":"100.00","base":"0","is_item":"1"}},{"MeasurableItem":{"header":"Total","is_item":false,"is_abbrev":false}},{"MeasurableItem":{"header":"P.S","tooltip":"Perfect Score","is_item":false,"is_abbrev":true}},{"MeasurableItem":{"header":"W.S","tooltip":"Weighted Score","is_item":false,"is_abbrev":true}}]}
			}
		);
});